# ===== PROD PROFILE =====
server.port=8081

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/blogdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=yourpassword

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Disable H2 Console
spring.h2.console.enabled=false

# Swagger (disable in prod if needed)
springdoc.swagger-ui.enabled=true
